// shared/network/update-check.js
// "Is there a newer Orbit?" — one implementation shared by desktop and mobile.
//
// Source of truth is GitHub Releases for the Orbit repo. Two things make that
// less trivial than it looks:
//
//   1. The release line is v0.5.x-beta and build.yml marks any tag containing
//      "beta"/"alpha" as a prerelease. GitHub's /releases/latest endpoint
//      EXCLUDES prereleases, so it would 404 for every current Orbit release.
//      We therefore list releases and pick the newest by semver ourselves.
//   2. Release bodies are generated by CI and contain Downloads/Installation/
//      Verify/Security/Links sections. Those are noise in an update dialog, so
//      parseHighlights() skips them.
//
// Pure logic (parseVersion / compareVersions / parseHighlights / pickAsset) is
// side-effect free and unit-tested in tests/unit/update-check.test.js.
//
// Exposes window.Orbit.UpdateCheck

window.Orbit = window.Orbit || {};

Orbit.UpdateCheck = (function() {
  var REPO = 'D4niel-dev/Orbit-beta';
  var RELEASES_API = 'https://api.github.com/repos/' + REPO + '/releases?per_page=15';
  var RELEASES_PAGE = 'https://github.com/' + REPO + '/releases';

  // Don't hammer the API: unauthenticated GitHub is 60 requests/hour per IP.
  var CHECK_INTERVAL_MS = 6 * 60 * 60 * 1000;
  var KEY_LAST_CHECK = 'orbit_update_lastCheck';
  var KEY_SKIPPED = 'orbit_update_skipped';

  /* ------------------------------------------------------------------ *
   * Version comparison
   * ------------------------------------------------------------------ */

  // 'v0.5.2-beta' -> { numbers: [0,5,2,0], prerelease: 'beta' }
  function parseVersion(v) {
    if (typeof v !== 'string') return null;
    var s = v.trim().replace(/^v/i, '');
    if (!s) return null;
    var m = s.match(/^(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:\.(\d+))?(?:[-+](.+))?$/);
    if (!m) return null;
    return {
      numbers: [m[1], m[2], m[3], m[4]].map(function(x) {
        return x === undefined ? 0 : parseInt(x, 10);
      }),
      prerelease: m[5] || ''
    };
  }

  // Semver prerelease ordering: numeric identifiers compare numerically and
  // rank below alphanumeric ones; a shorter set ranks below a longer one.
  function comparePrerelease(a, b) {
    var as = String(a).split('.');
    var bs = String(b).split('.');
    var len = Math.max(as.length, bs.length);
    for (var i = 0; i < len; i++) {
      var x = as[i];
      var y = bs[i];
      if (x === undefined) return -1;
      if (y === undefined) return 1;
      var xn = /^\d+$/.test(x);
      var yn = /^\d+$/.test(y);
      if (xn && yn) {
        var xi = parseInt(x, 10);
        var yi = parseInt(y, 10);
        if (xi !== yi) return xi < yi ? -1 : 1;
      } else if (xn !== yn) {
        return xn ? -1 : 1;
      } else if (x !== y) {
        return x < y ? -1 : 1;
      }
    }
    return 0;
  }

  // -1 if a < b, 0 if equal, 1 if a > b. Unparseable input sorts lowest.
  function compareVersions(a, b) {
    var pa = parseVersion(a);
    var pb = parseVersion(b);
    if (!pa && !pb) return 0;
    if (!pa) return -1;
    if (!pb) return 1;
    for (var i = 0; i < 4; i++) {
      if (pa.numbers[i] !== pb.numbers[i]) return pa.numbers[i] < pb.numbers[i] ? -1 : 1;
    }
    // Same numeric core: a plain release outranks a prerelease.
    if (!pa.prerelease && pb.prerelease) return 1;
    if (pa.prerelease && !pb.prerelease) return -1;
    if (pa.prerelease === pb.prerelease) return 0;
    return comparePrerelease(pa.prerelease, pb.prerelease);
  }

  /* ------------------------------------------------------------------ *
   * Release-body parsing
   * ------------------------------------------------------------------ */

  // Sections in the CI-generated body that are install/verify boilerplate
  // rather than "what changed".
  // Sections whose bullets are NOT user-facing. "Technical" matters: without it the
  // update dialog fills its six slots with internal notes ("Chunk storage changed
  // shape...") ahead of things a user would actually recognise.
  var SKIP_SECTION = /^(downloads?|installation|installation notes|verify|verify your download|security|links|assets|checksums?|technical|internal|notes?|migration)$/i;

  function stripMarkdown(s) {
    return String(s)
      .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')   // [text](url) -> text
      .replace(/`([^`]+)`/g, '$1')               // `code`
      .replace(/\*\*([^*]+)\*\*/g, '$1')         // **bold**
      .replace(/(^|\s)\*([^*]+)\*/g, '$1$2')     // *italic*
      .replace(/^\s*[-*+]\s+/, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function truncate(s, max) {
    if (s.length <= max) return s;
    return s.slice(0, max - 1).replace(/\s\S*$/, '') + '…';
  }

  // Pull the first `max` changelog bullets out of a release body, skipping the
  // boilerplate sections and the "Version: bumped to ..." technical noise.
  function parseHighlights(body, max) {
    if (!body || typeof body !== 'string') return [];
    max = max || 6;
    var out = [];
    var skipping = false;
    var lines = body.split(/\r?\n/);

    for (var i = 0; i < lines.length && out.length < max; i++) {
      var line = lines[i];
      var heading = line.match(/^#{1,4}\s+(.+)$/);
      if (heading) {
        var title = stripMarkdown(heading[1]).replace(/[:\-–—]+$/, '').trim();
        skipping = SKIP_SECTION.test(title);
        continue;
      }
      if (skipping) continue;
      var bullet = line.match(/^\s*[-*+]\s+(.+)$/);
      if (!bullet) continue;
      var text = stripMarkdown(bullet[1]);
      if (!text) continue;
      if (/^version\b/i.test(text)) continue;
      out.push(truncate(text, 220));
    }
    return out;
  }

  // CHANGELOG.md sections look like:
  //   ## v0.5.1-beta
  //   > **Note:** ...
  //   ### Bug Fixes
  //   - **Title** — description
  //   ## v0.5.0-beta — **Stable Release**
  // Returns the body of the section for `version`, or '' if absent.
  function sectionForVersion(md, version) {
    if (!md || typeof md !== 'string') return '';
    var want = String(version).replace(/^v/i, '').toLowerCase();
    var lines = md.split(/\r?\n/);
    var out = [];
    var capturing = false;

    for (var i = 0; i < lines.length; i++) {
      var h = lines[i].match(/^##\s+(.+)$/);
      if (h) {
        if (capturing) break;   // reached the next version — stop
        var title = stripMarkdown(h[1]).replace(/[—–-]+\s*$/, '').trim();
        var ver = title.split(/\s+/)[0].replace(/^v/i, '').toLowerCase();
        if (ver === want) capturing = true;
        continue;
      }
      if (capturing) out.push(lines[i]);
    }
    return out.join('\n');
  }

  function changelogUrl(tag) {
    return 'https://raw.githubusercontent.com/' + REPO + '/' +
      encodeURIComponent(String(tag)) + '/CHANGELOG.md';
  }

  /* ------------------------------------------------------------------ *
   * Platform / asset selection
   * ------------------------------------------------------------------ */

  function currentPlatform() {
    if (typeof window !== 'undefined' && window.Orbit && Orbit.env) {
      if (Orbit.env.isAndroid) return 'android';
      if (Orbit.env.isElectron) {
        var p = window.orbitAPI && window.orbitAPI.platform;
        if (p === 'darwin' || p === 'linux' || p === 'win32') return p;
        return 'win32';
      }
    }
    var ua = (typeof navigator !== 'undefined' && navigator.userAgent) || '';
    if (/Android/i.test(ua)) return 'android';
    if (/Mac OS X|Macintosh/i.test(ua)) return 'darwin';
    if (/Linux/i.test(ua)) return 'linux';
    return 'win32';
  }

  // Asset globs from electron-builder.yml / build.yml.
  var ASSET_MATCHERS = {
    android: /\.apk$/i,
    darwin: /\.dmg$/i,
    linux: /\.(appimage|deb)$/i,
    win32: /\.exe$/i
  };

  function _hasToken(name, tokens) {
    var lower = String(name).toLowerCase();
    for (var i = 0; i < tokens.length; i++) {
      if (lower.indexOf(tokens[i]) !== -1) return true;
    }
    return false;
  }

  // Arch tokens as they appear in electron-builder artifact names. Note x64
  // must NOT match "arm64": "arm64".indexOf("x64") is -1, so it does not.
  function _archTokens(arch) {
    var a = String(arch || '').toLowerCase();
    if (!a) return [];
    if (a === 'arm64' || a === 'aarch64') return ['arm64', 'aarch64'];
    if (a === 'x64' || a === 'amd64') return ['x64', 'x86_64', 'amd64'];
    if (a === 'ia32' || a === 'x86') return ['ia32', 'x86'];
    return [a];
  }

  // The format to prefer when a platform ships more than one.
  function _isPreferredFormat(name, platform) {
    // AppImage runs anywhere; a .deb needs dpkg and the matching distro.
    if (platform === 'linux') return /\.appimage$/i.test(name);
    return true;
  }

  // With no arch to go on, prefer the build that runs on BOTH kinds of Mac:
  // Rosetta 2 runs an x64 app on Apple Silicon, but an arm64 app will not run
  // on an Intel Mac at all.
  function _fallbackArchTokens(platform) {
    return platform === 'darwin' ? ['x64', 'x86_64', 'amd64'] : [];
  }

  // Pick the installer to hand the user.
  //
  // GitHub returns release assets in ALPHABETICAL order, not the order CI
  // uploaded them, so "first match wins" was never a preference — it was luck,
  // and it picked wrong against real releases:
  //   macOS -> arm64.dmg sorts before x64.dmg, so an Intel Mac was handed the
  //            Apple-silicon build, which will not launch
  //   Linux -> amd64.deb sorts before x86_64.AppImage, so the "runs anywhere"
  //            AppImage was never offered
  // Preference is explicit now: arch + preferred format, then arch, then
  // preferred format, then anything that matches.
  function pickAsset(release, platform, arch) {
    var assets = ((release && release.assets) || []).filter(function (a) {
      return a && a.name;
    });
    var want = ASSET_MATCHERS[platform] || ASSET_MATCHERS.win32;
    var candidates = assets.filter(function (a) { return want.test(a.name); });
    if (!candidates.length) return null;

    var tokens = _archTokens(arch);
    if (!tokens.length) tokens = _fallbackArchTokens(platform);
    var pick = null;

    if (tokens.length) {
      pick = candidates.filter(function (a) {
        return _hasToken(a.name, tokens) && _isPreferredFormat(a.name, platform);
      })[0];
      if (!pick) {
        pick = candidates.filter(function (a) { return _hasToken(a.name, tokens); })[0];
      }
    }
    if (!pick) {
      pick = candidates.filter(function (a) { return _isPreferredFormat(a.name, platform); })[0];
    }
    if (!pick) pick = candidates[0];

    return {
      name: pick.name,
      url: pick.browser_download_url,
      size: pick.size || 0
    };
  }

  /* ------------------------------------------------------------------ *
   * Current version
   * ------------------------------------------------------------------ */

  function currentVersion() {
    if (typeof window === 'undefined') return '0.0.0';
    // Mobile: version.js (generated from mobile/package.json at sync time).
    if (window.APP_VERSION) return String(window.APP_VERSION);
    if (window.orbitAPI) {
      // Prefer the main-process value: preload's legacy `version` field comes
      // from process.env.npm_package_version, which is unset in a packaged
      // build, so it silently falls back to a hardcoded string.
      if (typeof window.orbitAPI.getAppVersion === 'function') {
        try {
          var v = window.orbitAPI.getAppVersion();
          if (v) return String(v);
        } catch (e) { /* fall through */ }
      }
      if (window.orbitAPI.version) return String(window.orbitAPI.version);
    }
    return '0.0.0';
  }

  // CPU arch, used to pick the right macOS/Linux build. Electron's preload
  // exposes it; a browser (mobile) has no equivalent, so this returns '' there
  // and pickAsset falls back to its format preference alone.
  function currentArch() {
    if (typeof window !== 'undefined' && window.orbitAPI && window.orbitAPI.arch) {
      return String(window.orbitAPI.arch);
    }
    return '';
  }

  /* ------------------------------------------------------------------ *
   * Persistence (desktop Storage helper, or plain localStorage on mobile)
   * ------------------------------------------------------------------ */

  function readKey(key) {
    try {
      if (typeof window !== 'undefined' && window.Storage && window.Storage.get) {
        return window.Storage.get(key, null);
      }
      var raw = window.localStorage.getItem(key);
      return raw == null ? null : JSON.parse(raw);
    } catch (e) {
      return null;
    }
  }

  function writeKey(key, value) {
    try {
      if (typeof window !== 'undefined' && window.Storage && window.Storage.set) {
        window.Storage.set(key, value);
        return;
      }
      window.localStorage.setItem(key, JSON.stringify(value));
    } catch (e) { /* storage full or unavailable — non-fatal */ }
  }

  function removeKey(key) {
    try {
      if (typeof window !== 'undefined' && window.Storage && window.Storage.remove) {
        window.Storage.remove(key);
        return;
      }
      window.localStorage.removeItem(key);
    } catch (e) { /* non-fatal */ }
  }

  function shouldCheck(force) {
    if (force) return true;
    var last = readKey(KEY_LAST_CHECK);
    if (typeof last !== 'number') return true;
    return (Date.now() - last) >= CHECK_INTERVAL_MS;
  }

  function markChecked() { writeKey(KEY_LAST_CHECK, Date.now()); }
  function skippedVersion() { return readKey(KEY_SKIPPED); }
  function skipVersion(v) { writeKey(KEY_SKIPPED, String(v)); }
  function clearSkip() { removeKey(KEY_SKIPPED); }

  /* ------------------------------------------------------------------ *
   * Network
   * ------------------------------------------------------------------ */

  // Transport selection. Desktop's renderer cannot reach GitHub directly —
  // index.html pins a CSP whose connect-src omits api.github.com — so the main
  // process performs the request and this adapter reshapes the reply into
  // something that quacks like a Response. Mobile just uses window.fetch.
  function electronTransport() {
    if (typeof window === 'undefined' || !window.orbitAPI ||
        typeof window.orbitAPI.updateFetch !== 'function') {
      return null;
    }
    return function(url) {
      return window.orbitAPI.updateFetch(url).then(function(res) {
        if (!res || typeof res !== 'object') throw new Error('no response');
        if (!res.ok) throw new Error(res.error || ('GitHub responded ' + res.status));
        var body = typeof res.body === 'string' ? res.body : '';
        return {
          ok: true,
          status: res.status,
          json: function() {
            try { return Promise.resolve(JSON.parse(body)); }
            catch (e) { return Promise.reject(e); }
          },
          text: function() { return Promise.resolve(body); }
        };
      });
    };
  }

  // Mobile: Capacitor's built-in HTTP plugin performs the request in native
  // code, so it sidesteps WebView CORS entirely — which matters here because
  // the Android WebView runs on the https://localhost origin. Falls through to
  // window.fetch when the plugin is not registered (browser dev).
  function capacitorTransport() {
    if (typeof window === 'undefined' || !window.Capacitor ||
        !window.Capacitor.Plugins || !window.Capacitor.Plugins.CapacitorHttp) {
      return null;
    }
    var http = window.Capacitor.Plugins.CapacitorHttp;
    return function(url, init) {
      var headers = (init && init.headers) || {};
      return http.get({ url: url, headers: headers }).then(function(res) {
        var status = res && typeof res.status === 'number' ? res.status : 0;
        var data = res ? res.data : undefined;
        // CapacitorHttp parses JSON for us; re-stringify so json()/text() below
        // stay identical to the browser path.
        var body = typeof data === 'string' ? data : JSON.stringify(data === undefined ? '' : data);
        if (status < 200 || status >= 300) throw new Error('GitHub responded ' + status);
        return {
          ok: true,
          status: status,
          json: function() {
            try { return Promise.resolve(JSON.parse(body)); }
            catch (e) { return Promise.reject(e); }
          },
          text: function() { return Promise.resolve(body); }
        };
      });
    };
  }

  function resolveFetch(opts) {
    if (opts && typeof opts.fetchImpl === 'function') return opts.fetchImpl;
    var viaElectron = electronTransport();
    if (viaElectron) return viaElectron;
    var viaCapacitor = capacitorTransport();
    if (viaCapacitor) return viaCapacitor;
    if (typeof fetch === 'function') return fetch;
    return null;
  }

  function fetchReleases(opts) {
    opts = opts || {};
    var url = opts.url || RELEASES_API;
    var doFetch = resolveFetch(opts);
    if (!doFetch) return Promise.reject(new Error('no fetch transport'));

    var init = { cache: 'no-store', headers: { Accept: 'application/vnd.github+json' } };
    if (opts.token) init.headers.Authorization = 'Bearer ' + opts.token;

    return Promise.resolve(doFetch(url, init)).then(function(res) {
      if (!res.ok) throw new Error('GitHub responded ' + res.status);
      return res.json();
    }).then(function(list) {
      if (!Array.isArray(list)) throw new Error('unexpected payload');
      return list;
    });
  }

  function fetchText(url, opts) {
    opts = opts || {};
    var doFetch = resolveFetch(opts);
    if (!doFetch) return Promise.reject(new Error('no fetch transport'));
    var init = { cache: 'no-store' };
    if (opts.token) init.headers = { Authorization: 'Bearer ' + opts.token };
    return Promise.resolve(doFetch(url, init)).then(function(res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.text();
    });
  }

  // Newest published, non-draft release by semver. Prereleases are allowed on
  // purpose — the whole v0.5.x line is one.
  function pickLatest(releases) {
    var best = null;
    (releases || []).forEach(function(rel) {
      if (!rel || rel.draft) return;
      var tag = rel.tag_name || rel.name;
      if (!tag || !parseVersion(tag)) return;
      if (!best) { best = rel; return; }
      if (compareVersions(tag, best.tag_name || best.name) > 0) best = rel;
    });
    return best;
  }

  /* ------------------------------------------------------------------ *
   * Public entry points
   * ------------------------------------------------------------------ */

  // Full check. Never rejects — a network failure resolves to { ok: false }.
  function check(opts) {
    opts = opts || {};
    var current = opts.currentVersion || currentVersion();
    var platform = opts.platform || currentPlatform();
    var arch = opts.arch || currentArch();
    var maxHighlights = opts.maxHighlights || 6;

    function build(rel, highlights) {
      var latest = String(rel.tag_name || rel.name || '').replace(/^v/i, '');
      var asset = pickAsset(rel, platform, arch);
      return {
        ok: true,
        current: current,
        latest: latest,
        hasUpdate: compareVersions(latest, current) > 0,
        name: rel.name || rel.tag_name || latest,
        publishedAt: rel.published_at || null,
        releaseUrl: rel.html_url || RELEASES_PAGE,
        highlights: highlights,
        prerelease: !!rel.prerelease,
        platform: platform,
        asset: asset,
        // Falling back to the release page keeps the button useful even when a
        // platform artifact is missing from a build.
        downloadUrl: asset ? asset.url : (rel.html_url || RELEASES_PAGE),
        releasesPage: RELEASES_PAGE
      };
    }

    return fetchReleases(opts).then(function(list) {
      var rel = pickLatest(list);
      if (!rel) {
        return { ok: true, current: current, platform: platform, hasUpdate: false, reason: 'no-releases' };
      }

      // Release bodies generated by build.yml contain only the download table
      // and install/verify boilerplate — no changelog. Prefer them when they do
      // carry notes, otherwise read CHANGELOG.md at the tag, which is the
      // curated source and works for every release already published.
      var fromBody = parseHighlights(rel.body, maxHighlights);
      if (fromBody.length) return build(rel, fromBody);

      var tag = rel.tag_name || rel.name;
      return fetchText(changelogUrl(tag), opts).then(function(md) {
        return build(rel, parseHighlights(sectionForVersion(md, tag), maxHighlights));
      }).catch(function() {
        // A missing changelog must not fail the whole check — the version and
        // download link are still useful on their own.
        return build(rel, []);
      });
    }).catch(function(err) {
      return {
        ok: false,
        current: current,
        platform: platform,
        hasUpdate: false,
        error: String((err && err.message) || err)
      };
    });
  }

  // Boot path: respects the 6h throttle and the user's "skip this version".
  function checkThrottled(opts) {
    opts = opts || {};
    var current = opts.currentVersion || currentVersion();

    if (!shouldCheck(opts.force)) {
      return Promise.resolve({
        ok: true, current: current, hasUpdate: false, reason: 'throttled'
      });
    }

    return check(opts).then(function(res) {
      markChecked();
      if (res.ok && res.hasUpdate && !opts.force && skippedVersion() === res.latest) {
        return {
          ok: true, current: res.current, latest: res.latest,
          hasUpdate: false, reason: 'skipped', suppressed: res
        };
      }
      return res;
    });
  }

  return {
    REPO: REPO,
    RELEASES_API: RELEASES_API,
    RELEASES_PAGE: RELEASES_PAGE,
    CHECK_INTERVAL_MS: CHECK_INTERVAL_MS,

    parseVersion: parseVersion,
    compareVersions: compareVersions,
    parseHighlights: parseHighlights,
    sectionForVersion: sectionForVersion,
    changelogUrl: changelogUrl,
    pickAsset: pickAsset,
    pickLatest: pickLatest,
    stripMarkdown: stripMarkdown,

    currentVersion: currentVersion,
    currentPlatform: currentPlatform,
    electronTransport: electronTransport,
    capacitorTransport: capacitorTransport,
    fetchReleases: fetchReleases,
    fetchText: fetchText,
    check: check,
    checkThrottled: checkThrottled,

    shouldCheck: shouldCheck,
    markChecked: markChecked,
    skippedVersion: skippedVersion,
    skipVersion: skipVersion,
    clearSkip: clearSkip
  };
})();
